version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: sample-mysql57
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 13306:3306
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
